print("Plotting Basics: Simren Batra")
install.packages("FSA")
install.packages("FSAdata")
install.packages("magrittr")
install.packages("dplyr")
install.packages("plotrix")
install.packages("ggplot2")
install.packages("moments")
library(FSA)
library(FSAdata)
library(magrittr)
library(plotrix)
library(ggplot2)
library(moments)
library(dplyr)
head(data,3)
tail(data,3)
BullTroutRML2
FilteredBullTroutRML2 <- filterD(BullTroutRML2,BullTroutRML2$lake == "Harrison")
FilteredBullTroutRML2
head(FilteredBullTroutRML2,5)
tail(FilteredBullTroutRML2,5)
str(FilteredBullTroutRML2)
summary(FilteredBullTroutRML2)
xlim=c(0,500)
ylim=c(0,15)
attach(FilteredBullTroutRML2)
plot(age~fl,main="Plot 1: Harrison Lake Trout",xlim=xlim,ylim=ylim,xlab="Fork Length(mm)",ylab="Age(yrs)",pch=20)
hist(age,ylab="Frequency",xlab="Age(yrs)",main="Plot 2:Harrison Fish Age Distribution", xlim =ylim,ylim =ylim ,col ="cadetblue",col.main="cadetblue")
plot(age ~ fl, main="Plot 3: Harrison Density Shaded by Era", xlab="Fork Length (mm)",
     ylab="Age (yrs)", xlim=xlim, ylim=ylim, pch=19, col=c("darkgreen", "lightgreen"))
legend(x = "topleft", legend = paste(levels(BullTroutRML2$era)), col=c("deeppink3", "cyan1"), pch = 19)
tmp <- headtail(FilteredBullTroutRML2,3)
tmp$era
pchs <- c("+","x")
cols <- c("red", "gray60")
initialize(cols,tmp$era)
plot(age~fl,main = "Plot 4: Symbol & Color by Era",xlim = xlim,ylim =ylim,ylab="Fork Length(mm)",xlab="Age(yrm)",pch=pchs,col=cols)
plot(age~fl,main = "Plot 5: Regression Overlay",xlim = xlim,ylim =ylim,ylab="Fork Length(mm)",xlab="Age(yrm)",pch=pchs,col=cols)
abline(lm(age~fl))
plot(age~fl,main = "Plot 6: :Legend Overlay",xlim = xlim,ylim =ylim,ylab="Fork Length(mm)",xlab="Age(yrm)",pch=pchs,col=cols)
abline(lm(age~fl))
legend(x = "topleft", legend = paste(levels(BullTroutRML2$era)), col=cols, pch = pchs)



